name: Deploy Spring Boot 3
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/simple-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/

      - name: Upload JAR via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/simple-0.0.1-SNAPSHOT.jar"
          target: "/www/app_service/"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source /etc/profile
            cd /www/app_service/
            # 终止旧进程
            kill $(lsof -t -i:8080) || true
            sleep 2
            # 启动新进程并脱离终端
            nohup java -jar target/simple-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 & disown
            # 验证进程是否启动
            sleep 5
            if pgrep -f 'java.*simple-0.0.1-SNAPSHOT.jar' >/dev/null; then
              echo "应用启动成功"
            else
              echo "应用启动失败"
              exit 1
            fi