name: Deploy SpringBoot3
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: simple-app
  IMAGE_FULL_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-app:latest

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_FULL_NAME: ${{ steps.variables.outputs.IMAGE_FULL_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false

  push-docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.IMAGE_FULL_NAME }}
          push: true

  deploy:
    runs-on: ubuntu-latest
    needs: push-docker

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop ${{ env.IMAGE_NAME }} 2>/dev/null
            docker rm ${{ env.IMAGE_NAME }} 2>/dev/null
            docker rmi ${{ env.IMAGE_FULL_NAME }} || true

            docker pull ${{ env.IMAGE_FULL_NAME }}
            docker run -d \
              --name ${{ env.IMAGE_NAME }} \
              --restart unless-stopped \
              -p 8080:8080 \
              ${{ env.IMAGE_FULL_NAME }}
